name: fitness_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  introduction_screen: ^1.0.7
  http: ^0.12.0+2
  sleek_circular_slider: ^1.0.7
  cached_network_image: ^2.0.0-rc.1
  audioplayers: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.4"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "assets/logo_background.png"
  adaptive_icon_foreground: "assets/logo_foreground.png"

flutter:

  uses-material-design: true

  assets:
    - assets/